# Generated by Django 4.0.4 on 2022-08-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('code_phone', models.IntegerField(verbose_name='код')),
                ('teg', models.CharField(max_length=50, verbose_name='Фильтр Тэг')),
                ('time_zone', models.IntegerField(verbose_name='Временная зона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Delivary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField(verbose_name='Начало рассылки')),
                ('date_time_stop', models.DateTimeField(verbose_name='Конец рассылки')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('filter_code', models.IntegerField(verbose_name='Фильтр код')),
                ('filter_teg', models.CharField(max_length=50, verbose_name='Фильтр Тэг')),
                ('count_send_yes', models.IntegerField(verbose_name='Сообщений доставлено')),
                ('count_send_no', models.IntegerField(verbose_name='Сообщений НЕ доставлено')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_send', models.DateTimeField(verbose_name='Время рассылки')),
                ('status', models.TextField(choices=[('SEND', 'Отправлено'), ('NO SEND', 'Не отправлено')], default='NO SEND')),
                ('response_code', models.IntegerField(verbose_name='код ответа')),
                ('response_message', models.TextField(verbose_name='Сообщение ответа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='polls.client')),
                ('delivary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='polls.delivary')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['status'],
            },
        ),
    ]
